### ISSUE TITLE
ISSUE: You do not have a discord

### ISSUE THREAD

**Issue by genosmrpg7899** [bluepilledgreat/open-roblosium#2]
POSSIBLE FIX: Provide other means of contacting you
IN RETURN: NOThing

MY EMAIL: crazyfrog@chemist.com
MY DISCORD TAG (PROBABLY USELESS): genosmrpg7899#2369
MY ROBLOX USERNAME (BECAUSE): HeadphoneGaming1

Thx

**Comment by bluepilledgreat** [comment]
Keep an eye on my Github, I'm also attempting to appeal my false Discord ban at the current moment.
